name: Helm Chart Linting
on:
  push
    branches:
      - main
  pull-request:
    branches:
      - main

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: latest

      - name: Run Helm Lint
        run: |
          helm lint ./helm/time-server
          helm lint ./helm/auth-server
